[browser]
gatherUsageStats = false

[theme]
primaryColor="#f05252"
backgroundColor="#ffffff"  # Changed to light background color
secondaryBackgroundColor="#f0f0f0"  # Changed to light secondary background color
textColor="#000000"  # Changed to dark text color for better contrast
base = "light"